### ISSUE TITLE
pytflib not found

### ISSUE THREAD

**Issue by jhoang314** [deepmind/gqn-datasets#1]
https://github.com/deepmind/gqn-datasets/blob/72590cdbd5fe3972b95663a99ee92bca009252b5/data_reader.py#L23

I can't find any reference to pytflib on Google or PyPi. Is that an internal thing. I found a commit that's replacing sonnet.python.ops.next with pytflib.nest. What's the equivalent of `pytflib.nest.map_structure` in sonnet?

Thanks

**Comment by fabioviola** [comment]
Hello jhoang314,

Thank you for flagging the issue. I just pushed an update that should solve it.
Please reopen if you still have problems!

Cheers,
Fabio
