### ISSUE TITLE
GQN official implementation

### ISSUE THREAD

**Issue by phongnhhn92** [deepmind/gqn-datasets#11]
Hello, it has been a while so I would like to ask is there any plan to release the public code as long as the trained model ?

**Comment by NotAnyMike** [comment]
Looks like no but there are several independent implementations. Look at [this](https://github.com/ogroth/tf-gqn) for example

**Comment by phongnhhn92** [comment]
Yeah right, Thanks to this implementation. I have written an improved GQN paper. I guess I will close this issue now. https://arxiv.org/abs/1904.05124
