### ISSUE TITLE
Download GQN Dataset

### ISSUE THREAD

**Issue by ogroth** [deepmind/gqn-datasets#2]
Hi,
I was wondering how to download the GQN training and test data from https://console.cloud.google.com/storage/browser/gqn-dataset/
There is no obvious download link for the directories. The tfrecord files can be downloaded individually, but this is clearly infeasible for 10k+ files. Is there an easier way to do this without having to scrape the URLs?
Thanks,
Oliver

**Comment by fabioviola** [comment]
Hello Olivier,
I think you can use [this tool](https://cloud.google.com/storage/docs/gsutil/commands/cp), which you can install following [these instructions](https://cloud.google.com/storage/docs/gsutil_install).
I hope this helps; if you are still stuck please reopen the issue.
Cheers,
Fabio

**Comment by mjchen611** [comment]
@fabioviola 
Hello fabioviola,

I was wondering how to download the GQN training and test data from the link
https://console.cloud.google.com/storage/browser/gqn-dataset/.
Even you have give some suggestions, I am still stuck (windows platform).
Is there  an another way to download this dataset?
Thank you.
Mingjia

**Comment by fabioviola** [comment]
Hi Mingjia,

What is excalty the issue? The [install gsutill](https://cloud.google.com/storage/docs/gsutil_install) webpage has instructions for Windows.
Once the tool is installed you should be able to copy the data using a command like:
gsutil cp -r gs://gqn-dataset your_data_directory

Is this working for you?
Cheers,
Fabio
