### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by mjchen611** [deepmind/gqn-datasets#7]
Hello fabioviola,

I was wondering how to download the GQN training and test data from the link
https://console.cloud.google.com/storage/browser/gqn-dataset/.
Even you have give some suggestions, I am still stuck (windows platform).
Is there an another way to download this dataset?
Thank you.
Mingjia

**Comment by fabioviola** [comment]
Hi Mingjia,

What is excalty the issue? The [install gsutill webpage](https://cloud.google.com/storage/docs/gsutil_install) has instructions for Windows.
Once the tool is installed you should be able to copy the data using a command like:
`
gsutil cp -r gs://gqn-dataset your_data_directory
`
Is this working for you? Are you having [credential issues](https://cloud.google.com/storage/docs/gsutil/addlhelp/AccessingPublicDataWithoutCredentials)?

Cheers,
Fabio

**Comment by mjchen611** [comment]
Yes, it is working now.
Thank you for your kind assistance.

Best,
Mingjia

**Comment by fabioviola** [comment]
You're welcome, @mjchen611!
