### ISSUE TITLE
Incorrect file paths

### ISSUE THREAD

**Issue by augustelalande** [deepmind/gqn-datasets#8]
It seems the `_get_dataset_files` method generates filenames from `0` to ` num_files - 1`. e.g.

`root/shepard_metzler_5_parts/train/000-of-900.tfrecord`
to
`root/shepard_metzler_5_parts/train/899-of-900.tfrecord`

however the files on google cloud are numbered from `1` to `num_files`

`root/shepard_metzler_5_parts/train/001-of-900.tfrecord`
to
`root/shepard_metzler_5_parts/train/900-of-900.tfrecord`

this causes training to crash when the program tries to access the missing 0th file.

**Comment by fabioviola** [comment]
Thank you for catching this, Auguste.
The issue has now been fixed.
